version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://gslcloudpaneldata:CDpp8xFm9a7SNC41z8jW@host.docker.internal:3306/opportunity
    extra_hosts:
      - "host.docker.internal:host-gateway"
